name: toesteldelen_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.1+14
  connectivity_plus: ^5.0.2
  flutter_osm_plugin: ^1.3.7
  image_picker: ^1.0.7
  provider: ^6.1.1
  intl: ^0.18.1  # Downgraded to ensure compatibility with SDK
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  geolocator: ^10.1.0  # Downgraded to ensure compatibility with SDK
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true